make additional picards optional
Exawind/exawind-driver pull request #23
Opened 2022-05-05 22:27 UTC by ashesh2512

2022-05-05 22:27 UTC, ashesh2512 commented
Issue #22

2022-05-05 23:20 UTC, marchdf requested changes

2022-05-05 23:20 UTC, marchdf commented on app/exawind/exawind.cpp
> +        int additional_picard_its = 0;
can we do
```
const int additional_picard_its = node["additional_picard_iterations"]? node["additional_picard_iterations"].as<int>() : 0;
```

2022-05-06 03:32 UTC, marchdf approved these changes

2022-05-09 21:35 UTC, michaeljbrazell approved these changes

2022-05-10 15:42 UTC, merged