Test case that shows problem with Nalu-Tioga link
Exawind/exawind-driver pull request #69
Opened 2024-03-22 20:05 UTC by mbkuhn

In Nalu-Wind, the velocity is set to 0.0 and the density is set to 1.0. In AMR-Wind, the velocity is set to [0.1, -0.1, 0.0] and the density is set to 1.5. This shows that when multiple processors are used for Nalu-Wind, there are errors in communicating the fields properly into Nalu-Wind. The iblank field (its boundary shown in black), does not have issues, though, thanks to the recent changes to Nalu-Wind.

![Screenshot 2024-03-22 at 2 03 30 PM](https://github.com/Exawind/exawind-driver/assets/31661049/ff2bdf8e-5498-4ba9-9140-597d7395a304)

2024-03-24 23:04 UTC, itopcuoglu approved these changes

2024-03-25 13:49 UTC, psakievich requested changes
See not about solvers. Also let's not put a mesh file in this repository. Push it to the meshes repo please.

2024-03-25 13:49 UTC, psakievich commented on test/test_files/tioga-test/tiogatest-nalu.yaml
> +    type: tpetra
Can we switch these to hypre? These tpetra solver settings are super old and we've not been keeping up with them. I would rather not see another copy of `milestone.xml` put under version control if we can avoid it.

2024-03-25 15:51 UTC, mbkuhn commented
Thanks for the input, @psakievich. I wanted a quick way to share it with Ilker, so I put it all here at first. I'll make the changes you requested.

2024-03-25 15:58 UTC, psakievich commented
Sounds good. My requests are only if you want to merge it for a long term test. Otherwise, fine as is.

2024-03-25 16:01 UTC, mbkuhn commented
It probably would be useful to be added as a long-term part of the repository, but it doesn't fit well as a true regression test because it's just a one time step thing without a real physical meaning. I'll think about it some more.

2024-08-05 15:21 UTC, mbkuhn commented
Solved with nalu-wind fix related to "set_resolutions" https://github.com/Exawind/nalu-wind/pull/1267

2024-08-05 15:21 UTC, closed without merging