added memory usage utility
Exawind/exawind-driver pull request #7
Opened 2021-07-22 16:19 UTC by michaeljbrazell

2021-07-22 16:31 UTC, marchdf commented on src/OversetSimulation.cpp
> +    /* convert to MB */
can we convert comments to just `//` ?

2021-07-22 16:32 UTC, marchdf commented on src/OversetSimulation.cpp
> +    long memall[psize];
can we use `vector` instead of C arrays?

2021-07-22 16:35 UTC, marchdf commented on src/OversetSimulation.cpp
> +        char filename[] = "memusage.dat";
replace with `std::string`?

2021-07-22 16:35 UTC, marchdf commented on src/OversetSimulation.cpp
> +        fp = fopen(filename,"a");
Use a more c++ way for outputting to a file?

2021-07-22 20:42 UTC, marchdf commented on src/ExawindSolver.h
> +        long mem = (long) ((double) usage.ru_maxrss)/1024.0;
`const` this?

2021-07-22 20:43 UTC, marchdf commented on src/OversetSimulation.cpp
> +    long mem = (long) ((double) usage.ru_maxrss)/1024.0;
const this?

2021-07-26 17:24 UTC, marchdf requested changes

2021-07-26 17:24 UTC, marchdf commented on src/OversetSimulation.cpp
> +#include <sys/resource.h>
can we ifdef this stuff for linux?

2021-07-26 17:24 UTC, marchdf commented on src/ExawindSolver.h
> +#include <sys/resource.h>
can we ifdef this stuff for linux?

2021-07-26 17:24 UTC, marchdf commented on src/OversetSimulation.cpp
> +    struct rusage usage;
This has a lot in common with the other call in ExawindSolver. Can we maybe consolidate the memory stuff in a separate file? and then put the ifdefs there? That way we we ever want to update the memory stuff for other platforms we can just look at that file.

2021-07-28 15:38 UTC, marchdf approved these changes

2021-07-28 15:46 UTC, marchdf commented
This is super cool and we can merge if Mike is happy with my edits!

2021-07-28 17:01 UTC, michaeljbrazell commented
yeah that looks good!

2021-08-03 20:45 UTC, merged